# Local PostgreSQL (or use H2 for simpler testing)
#spring.datasource.url=jdbc:postgresql://localhost:5432/bh
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true